### ISSUE TITLE
knp_generator issues 500 Internal server error

### ISSUE THREAD

**Issue by rob-samson** [SamsonIT/DataGridBundle#3]
page navigation fails with 500 error.
Either by changing page number directly or by pressing page navigation arrow button.

Url called:
.../locationcrud?config=...&page=11&sort=undefined&direction=undefined&_format=json

Error is caused because sort=undefined and/or direction=undefined is unacceptable to the server side code.

Solution: in case sort or direction is not defined or is empty, then do not include them in the url.

**Comment by SchizoDuckie** [comment]
Fixed with 4615c886fb550460ef0cf4ed80b4b348b6527a0c . It should land on packagist soon.
