### ISSUE TITLE
Error 405 (Method not Allowed)

### ISSUE THREAD

**Issue by rob-samson** [SamsonIT/DataGridBundle#5]
Error 405 (Method Not Allowed) is caused by page navigation, either by pressing the arrow button or by changing the page number:

POST http://localhost:8000/locationcrud?config=Shifter%5CShiftBundle%5CEntity%5CLocation&page=5&_format=json 405 (Method Not Allowed)

Entering text in the filter box also causes this error:

POST http://localhost:8000/locationcrud?config=Shifter%5CShiftBundle%5CEntity%5C…e.name&filterField%5B%5D=e.parent&filterValue%5B%5D=tr&page=1&_format=json 405 (Method Not Allowed)

**Comment by SchizoDuckie** [comment]
Fixed with next release.
